const months = {
  "Oct-25": { recipient:"ZUHAIR ALSAFFAR", users:["HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Nov-25": { recipient:"HUSAIN YUSUF", users:["ZUHAIR ALSAFFAR","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Dec-25": { recipient:"HABIB KHAMIS", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Jan-26": { recipient:"ABU ADEL", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Feb-26": { recipient:"HASAN SAHWAN", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","RAJA","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Mar-26": { recipient:"RAJA", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","UM AHMED","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "Apr-26": { recipient:"UM AHMED", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","JAFFAR JUMA","ABU HASAN1","ABU HASAN2"] },
  "May-26": { recipient:"JAFFAR JUMA", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","ABU HASAN1","ABU HASAN2"] },
  "Jun-26": { recipient:"ABU HASAN", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA"] },
  "Jul-26": { recipient:"ABU HASAN", users:["ZUHAIR ALSAFFAR","HUSAIN YUSUF","HABIB KHAMIS","ABU ADEL","HASAN SAHWAN","RAJA","UM AHMED","JAFFAR JUMA"] }
};
